name: Crawl

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler Automatic Crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.0
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          github-token: ${{ github.token }}
          crawler-name: 'simpowater'
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          site-url: 'https://www.simpowater.org/docs'

# name: algolia-docsearch-scraper

# on:
#   push:
#     branches: [master]
#   # pull_request:
#   #  branches: [master]

# jobs:
#   scan:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Sleep for 10 seconds
#         run: sleep 10s
#         shell: bash

#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Run scraper
#         env:
#           APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
#           API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
#         run: |
#           CONFIG="$(cat docsearch-config.json)"
#           docker run -i --rm \
#                   -e APPLICATION_ID=$APPLICATION_ID \
#                   -e API_KEY=$API_KEY \
#                   -e CONFIG="${CONFIG}" \
#                   algolia/docsearch-scraper
